# Generated by Django 3.1.7 on 2021-03-19 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('lang', models.FloatField()),
                ('lat', models.FloatField()),
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('walkable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Structural',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.buildings')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.coordinate')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='map.coordinate')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='map.coordinate')),
            ],
        ),
        migrations.CreateModel(
            name='LocationPoint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=200)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.coordinate')),
            ],
        ),
        migrations.AddField(
            model_name='buildings',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.coordinate'),
        ),
    ]
