# Generated by Django 3.1.5 on 2021-03-25 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('walkable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LocationPoint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('desciption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('types', models.CharField(max_length=10)),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Structural',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.buildings')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.coordinate')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('length', models.FloatField(blank=True)),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='map.coordinate')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='map.coordinate')),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_name', models.ImageField(upload_to='locationimage/')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.locationpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='locationpoint',
            name='marker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.marker'),
        ),
        migrations.AddField(
            model_name='locationpoint',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.coordinate'),
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thruesday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('openingtime', models.TimeField()),
                ('closingtime', models.TimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.locationpoint')),
            ],
        ),
    ]
