# Generated by Django 3.1.7 on 2021-03-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildings',
            name='point',
        ),
        migrations.AddField(
            model_name='buildings',
            name='key',
            field=models.CharField(default='0000', max_length=10, unique=True),
        ),
    ]
