# Generated by Django 3.1.7 on 2021-03-25 15:56

from django.db import migrations, models
import django.db.models.deletion
import map.models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20210325_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='locationpoint',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='street',
            name='end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='map.coordinate', validators=[map.models.Street.pointValidation]),
        ),
        migrations.AlterField(
            model_name='street',
            name='start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='map.coordinate', validators=[map.models.Street.pointValidation]),
        ),
        migrations.AlterField(
            model_name='structural',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
