# Generated by Django 3.1.7 on 2021-04-05 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import map.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0003_auto_20210325_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildings',
            name='marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.marker'),
        ),
        migrations.AddField(
            model_name='marker',
            name='color',
            field=models.CharField(default='grey', max_length=50),
        ),
        migrations.AlterField(
            model_name='locationpoint',
            name='desciption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='structural',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structural', to='map.buildings'),
        ),
        migrations.AlterField(
            model_name='structural',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.coordinate', validators=[map.models.Structural.pointValidation]),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('star', models.IntegerField()),
                ('total_like', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.locationpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pictures',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.review'),
        ),
    ]
