# Generated by Django 3.1.7 on 2021-04-05 13:43

from django.db import migrations, models
import map.models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20210405_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpoint',
            name='avg_star',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='locationpoint',
            name='no_of_review',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='locationpoint',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.IntegerField(validators=[map.models.Review.checkLike]),
        ),
        migrations.AlterField(
            model_name='review',
            name='total_like',
            field=models.IntegerField(default=0),
        ),
    ]
