# Generated by Django 3.1.7 on 2021-04-05 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20210405_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.locationpoint'),
        ),
    ]
